services:
  - type: web
    name: saxapahaw-timebank
    runtime: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: python -m gunicorn timebank.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - fromGroup: timebank-env
