services:
  - type: web
    name: saxfwd-community-time-bank
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd theme/static_src && npm install && npm run build && cd ../..
    startCommand: >
      python manage.py tailwind build &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py seed_db &&
      gunicorn timebank.wsgi:application
    envVars:
      - fromGroup: timebank-env
