services:
  - type: web
    name: timebank-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      cd theme && npm install && npm run build && cd ..
    startCommand: >
      python manage.py tailwind build &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      python manage.py shell -c "
        from django.contrib.auth import get_user_model;
        User = get_user_model();
        if not User.objects.filter(username='admin').exists():
            User.objects.create_superuser('admin', 'admin@example.com', 'supersecurepass')
        " &&
      gunicorn timebank.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: '{{ env.DJANGO_SECRET_KEY }}'
      - key: DEBUG
        value: '{{ env.DEBUG}}'
