# Generated by Django 5.0.2 on 2025-07-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebankledger',
            name='transaction_type',
            field=models.CharField(choices=[('service_credit', 'Service Credit'), ('service_debit', 'Service Debit'), ('community_donation', 'Community Donation'), ('community_request', 'Community Request'), ('request_credit', 'Request Credit'), ('request_debit', 'Request Debit'), ('application_credit', 'Application Approval Credit')], max_length=20),
        ),
    ]
