# Generated by Django 5.0.2 on 2025-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='hours_completed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
