# Generated by Django 5.0.2 on 2025-06-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hourly_rate',
        ),
    ]
