# Generated by Django 5.0.2 on 2025-07-20 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_timebankledger_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityhours',
            name='total_hours',
        ),
    ]
