# Generated by Django 5.0.2 on 2025-06-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_service_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_hours_earned',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_hours_spent',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
