# Generated by Django 5.0.2 on 2025-06-13 05:31

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timebankledger',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicerequest'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to=core.models.User.user_image_path),
        ),
    ]
