# Generated by Django 5.0.2 on 2025-07-21 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_total_hours_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='urgency',
            new_name='priority',
        ),
    ]
