# Generated by Django 5.0.2 on 2025-07-21 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_urgency_request_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetransaction',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_transactions', to='core.service'),
        ),
    ]
