# Generated by Django 5.0.2 on 2025-06-29 01:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_servicerequest_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingNotes",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("meeting_date", models.DateField()),
                ("pdf_file", models.FileField(upload_to="meeting_notes/")),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Meeting Notes",
                "ordering": ["-meeting_date", "-created_at"],
            },
        ),
    ]
