# Generated by Django 5.0.2 on 2025-06-05 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='requester_completed',
            field=models.BooleanField(default=False),
        ),
    ]
