# Generated by Django 5.0.2 on 2025-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicerequest_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_hours_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_hours_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
