# Generated by Django 5.0.2 on 2025-07-27 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicetransaction_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='is_onboarded',
            new_name='is_orientation_completed',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='onboarded_at',
            new_name='orientation_at',
        ),
    ]
