# Generated by Django 5.0.2 on 2025-06-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meetingnotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingnotes',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='meetingnotes',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='meetingnotes',
            name='pdf_file',
            field=models.FileField(upload_to='uploads/meeting_notes/'),
        ),
    ]
