# Generated by Django 5.0.2 on 2025-07-02 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_is_onboarded_user_is_referral_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='reviewed_at',
            new_name='referral_approved_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_onboarded',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_referral_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarded_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_approved_by',
        ),
        migrations.AddField(
            model_name='application',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='is_referral_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='onboarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='referral_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
