# Generated by Django 5.0.2 on 2025-06-06 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_terms_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community Time Bank',
            },
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_request_reason',
            field=models.TextField(blank=True, help_text='Please explain why you need community hours'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_request_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_request_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_request_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_community_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='community_request_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_community_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timebankledger',
            name='transaction_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('community_donation', 'Community Donation'), ('community_request', 'Community Request')], max_length=20),
        ),
    ]
