from django.urls import path

from core.views.service import (
    ServiceCreateView,
    ServiceDeleteView,
    ServiceDetailView,
    ServiceEditView,
    ServiceListView,
    ServiceToggleActiveView,
    ServiceTransactionAcceptView,
    ServiceTransactionCancelView,
    ServiceTransactionCommunityHoursApproveView,
    ServiceTransactionCommunityHoursRejectView,
    ServiceTransactionCommunityHoursView,
    ServiceTransactionCompleteFormView,
    ServiceTransactionCompleteView,
    ServiceTransactionDetailView,
    ServiceTransactionRejectView,
    ServiceTransactionView,
)

urlpatterns = [
    path("", ServiceListView.as_view(), name="service_list"),
    path("create/", ServiceCreateView.as_view(), name="service_create"),
    path(
        "<uuid:pk>/",
        ServiceDetailView.as_view(),
        name="service_detail",
    ),
    path(
        "<uuid:pk>/edit/",
        ServiceEditView.as_view(),
        name="service_edit",
    ),
    path(
        "<uuid:pk>/delete/",
        ServiceDeleteView.as_view(),
        name="service_delete",
    ),
    path(
        "<uuid:pk>/toggle-active/",
        ServiceToggleActiveView.as_view(),
        name="service_toggle_active",
    ),
    path(
        "<uuid:pk>/transaction/",
        ServiceTransactionView.as_view(),
        name="service_transaction",
    ),
    path(
        "<uuid:pk>/",
        ServiceTransactionDetailView.as_view(),
        name="service_transaction_detail",
    ),
    path(
        "<uuid:pk>/accept/",
        ServiceTransactionAcceptView.as_view(),
        name="service_transaction_accept",
    ),
    path(
        "<uuid:pk>/reject/",
        ServiceTransactionRejectView.as_view(),
        name="service_transaction_reject",
    ),
    path(
        "<uuid:pk>/cancel/",
        ServiceTransactionCancelView.as_view(),
        name="service_transaction_cancel",
    ),
    path(
        "<uuid:pk>/complete/",
        ServiceTransactionCompleteFormView.as_view(),
        name="service_transaction_complete_form",
    ),
    path(
        "<uuid:pk>/complete-action/",
        ServiceTransactionCompleteView.as_view(),
        name="service_transaction_complete",
    ),
    path(
        "<uuid:pk>/community/",
        ServiceTransactionCommunityHoursView.as_view(),
        name="community_service_transaction",
    ),
    path(
        "<uuid:pk>/community/approve/",
        ServiceTransactionCommunityHoursApproveView.as_view(),
        name="community_service_transaction_approve",
    ),
    path(
        "<uuid:pk>/community/reject/",
        ServiceTransactionCommunityHoursRejectView.as_view(),
        name="community_service_transaction_reject",
    ),
]
